### PR TITLE
Added Project.toml and updates version

### PR DESCRIPTION
**Pull request by theogf**
Solves #15

### CODE REVIEW

**Comment by twavv** [comment]
Looks good. Can you also delete REQUIRE?

**Review by twavv — APPROVED** [review]

**Comment by twavv** [comment]
Actually wait - why are we bumping the version to 0.2.0? If there are no code changes, I'd rather just release 0.1.1 since that won't require updating any compat entries for other projects (e.g. Interact).

**Comment by theogf** [comment]
Oh yeah you're right! I wanted to bump a version but it doesn't need to be breaking!

**Comment by theogf** [comment]
Ok I applied the changes

**Pull request merged**
